/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__tut_pyx_sample
#define __PYX_HAVE__tut_pyx_sample


#ifndef __PYX_HAVE_API__tut_pyx_sample

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(double) node_x;
__PYX_EXTERN_C DL_IMPORT(double) node_y;
__PYX_EXTERN_C DL_IMPORT(double) node_z;
__PYX_EXTERN_C DL_IMPORT(double) node_vx;
__PYX_EXTERN_C DL_IMPORT(double) node_vy;
__PYX_EXTERN_C DL_IMPORT(double) node_vz;
__PYX_EXTERN_C DL_IMPORT(double) node_m;

#endif /* !__PYX_HAVE_API__tut_pyx_sample */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittut_pyx_sample(void);
#else
PyMODINIT_FUNC PyInit_tut_pyx_sample(void);
#endif

#endif /* !__PYX_HAVE__tut_pyx_sample */
